/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.game.component;

import lib.editor.data.game.AbstractData;
import lib.editor.ui.data.AbstractDatabasePanel;
import lib.editor.widget.inspector.InspectorPanel;

/**
 *
 * @author Gaetan
 */
public class RendererPanel extends InspectorPanel {

    private static RendererPanel instance;
    
    private RendererPanel() {
        super("Renderer", "renderer.png");
        initComponents();
    }

    public static RendererPanel instance(){
        if(instance == null){
            instance = new RendererPanel();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(AbstractDatabasePanel dataPanel, AbstractData data) {
        super.setup(dataPanel, data);
        
    }
    
    @Override
    public void refresh() {
    }
}
