/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.widget.inspector;

import lib.editor.data.game.AbstractData;
import lib.editor.data.game.MapData;
import lib.editor.ui.data.AbstractDatabasePanel;

/**
 *
 * @author Gaetan
 */
public class MapScenePanel extends InspectorPanel  {

    /**
     * Creates new form MapScenePanel
     */
    public MapScenePanel(Inspector inspector) {
        super(inspector, "Scene", "project_root.png");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sceneTree = new lib.editor.ui.data.map.SceneTree();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(sceneTree);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private lib.editor.ui.data.map.SceneTree sceneTree;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(AbstractDatabasePanel dataPanel, AbstractData data) {
        super.setup(dataPanel, data);
        
        MapData mapData = (MapData) data;
        sceneTree.setup(mapData.layers);
    }
    
    @Override
    public void refresh() {
        sceneTree.refresh();
    }
    
}
