/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui;

import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileSystemView;
import lib.editor.mgr.ProjectManager;
import lib.editor.util.SwingUtil;

/**
 *
 * @author gaetan
 */
public class ProjectWindow extends Dialog {

    private String projectPath;
    
    /**
     * Creates new form ProjectWindow
     */
    public ProjectWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        layoutDialog(12);
        
        
        setLocationRelativeTo(null);
        projectPath = "";
        refresh();
        
        folderNameTextField.getDocument().addDocumentListener(new DocumentListener(){  
            public void insertUpdate(DocumentEvent e) {
                if(!refreshing){
                    checkOkEnabled();
                    locationTextField.setText(completePath());
                }
            }

            public void removeUpdate(DocumentEvent e) {
                if(!refreshing){
                    checkOkEnabled();
                    locationTextField.setText(completePath());
                }
            }

            public void changedUpdate(DocumentEvent e) {}
        }); 
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        folderNameTextField = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        locationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel4 = new javax.swing.JPanel();
        warningLabel = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New project");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(350, 200));
        setModal(true);
        getContentPane().setLayout(new java.awt.GridLayout());

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/folder.png"))); // NOI18N
        jLabel1.setText("Folder name:");
        jPanel6.add(jLabel1);
        jPanel6.add(filler3);

        jPanel1.add(jPanel6);

        folderNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        folderNameTextField.setMinimumSize(new java.awt.Dimension(160, 28));
        folderNameTextField.setPreferredSize(new java.awt.Dimension(160, 28));
        jPanel1.add(folderNameTextField);

        mainPanel.add(jPanel1);
        mainPanel.add(filler2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 6, 0));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/folder_explore.png"))); // NOI18N
        jLabel3.setText("Project location:");
        jPanel7.add(jLabel3);
        jPanel7.add(filler4);

        jPanel3.add(jPanel7);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        locationTextField.setEditable(false);
        locationTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        locationTextField.setMinimumSize(new java.awt.Dimension(160, 28));
        locationTextField.setPreferredSize(new java.awt.Dimension(160, 28));
        jPanel2.add(locationTextField);

        browseButton.setText("...");
        browseButton.setMaximumSize(null);
        browseButton.setMinimumSize(null);
        browseButton.setPreferredSize(new java.awt.Dimension(32, 28));
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        jPanel2.add(browseButton);

        jPanel3.add(jPanel2);

        mainPanel.add(jPanel3);
        mainPanel.add(filler1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setText("sdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf");
        warningLabel.setAlignmentX(0.5F);
        jPanel4.add(warningLabel);

        mainPanel.add(jPanel4);
        mainPanel.add(filler6);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        File result = SwingUtil.getDirectoryChoice(this, projectPath, "Open folder");
        
        if(result != null){
            projectPath = result.getAbsolutePath();
            locationTextField.setText(completePath());
        }
        checkOkEnabled();
                
    }//GEN-LAST:event_browseButtonActionPerformed

    private void checkOkEnabled(){
        if(folderNameTextField.getText().equals("")){
            warningLabel.setText(" ");
            getDialogButton("ok").setEnabled(false);
        }
        else if(new File(completePath()).exists()){
            warningLabel.setText("A folder with that name already exists.");
            getDialogButton("ok").setEnabled(false);
        }
        else{
            warningLabel.setText(" ");
            getDialogButton("ok").setEnabled(true);
        }
        
    }
    
    
    private String completePath(){
        return (new File(projectPath, folderNameTextField.getText())).getAbsolutePath();
    }
    
    public void refresh(){
        refreshing = true;
        projectPath = defaultLocation();
        folderNameTextField.setText("");
        locationTextField.setText(projectPath);
        checkOkEnabled();
        refreshing = false;
    }
        
    private String defaultLocation(){
             JFileChooser fr = new JFileChooser();
            FileSystemView fw = fr.getFileSystemView();
            return fw.getDefaultDirectory().getAbsolutePath();
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JTextField folderNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables

    public void ok() {
        ProjectManager.createNewProject(completePath());
        super.ok();
    }

    /*
    @Override
    public boolean cancel() {
        return true;
    }*/

    @Override
    public JPanel getMainPanel() {
        return mainPanel;
    }
}
