/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui.data.tileset;

import java.util.List;

/**
 *
 * @author gaetan
 */
public class TilesetMiddlePanel extends javax.swing.JPanel {

    public TilesetList tilesetList;
    /**
     * Creates new form TilesetChoicesPanel
     */
    public TilesetMiddlePanel() {
        initComponents();
        tilesetList = new TilesetList();
        //add(tilesetListScrollPane);
        tilesetListScrollPane.setViewportView(tilesetList);
    }

    public void setup(List<String> tilesetFilenames){
        tilesetList.setup(tilesetFilenames);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tilesetListScrollPane = new javax.swing.JScrollPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("jButton1");
        add(jButton1);
        add(tilesetListScrollPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane tilesetListScrollPane;
    // End of variables declaration//GEN-END:variables
}
