/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui.assetmanager;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author gaetan
 */
public class AssetManagerScriptEditorPanel extends javax.swing.JPanel {

    private RSyntaxTextArea textEditor;
    private RTextScrollPane textEditorScrollPane;
    
    public AssetManagerScriptEditorPanel() {
        initComponents();
        
        textEditor  = new RSyntaxTextArea();
        textEditor.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_RUBY);
        textEditor.setEditable(false);
        
        textEditorScrollPane = new RTextScrollPane();
        textEditorScrollPane.setViewportView(textEditor);

        add(textEditorScrollPane);
        
    }

    public void setAsset(File file){
        setVisible(true);
        
        FileReader reader = null;
        try {
            reader = new FileReader(file.getAbsolutePath());
            textEditor.read(reader, file.getAbsolutePath());
        } catch (FileNotFoundException ex) {
            System.err.println("AssetManagerWindow -> setAsset() -> failed to read text asset file");
        } catch (IOException e) {
            System.err.println("AssetManagerWindow -> setAsset() -> failed to read text asset file");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
