/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui.assetmanager;

import java.awt.Frame;
import java.io.File;
import java.util.List;
import java.util.Properties;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import lib.editor.mgr.AppMgr;
import lib.editor.mgr.ProjectMgr;
import lib.editor.ui.Dialog;
import lib.editor.ui.MainWindow;
import lib.editor.util.Cst;
import lib.editor.util.SwingUtil;
import lib.editor.widget.tree.item.FilePathTreeItem;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author gaetan
 */
public class AssetManagerWindow extends Dialog {

    private static AssetManagerWindow instance;
    public static AssetManagerWindow getInstance(){
        if(instance == null){
            instance = new AssetManagerWindow(MainWindow.getInstance());
        }
        return instance;
    }
    
    boolean readOnly;
    String defaultFilename;
    List<String> formatFilter;
    

    
    private AssetManagerAudioPanel audioPanel;
    private AssetManagerScriptEditorPanel scriptPanel;
    private AssetManagerGraphicsPanel graphicsPanel;
    
    private AssetManagerWindow(Frame parent) {
        super(parent, true);
        initComponents();
        
        audioPanel = new AssetManagerAudioPanel();
        scriptPanel = new AssetManagerScriptEditorPanel();
        graphicsPanel = new AssetManagerGraphicsPanel();
        
        assetContainer.add(audioPanel);
        assetContainer.add(scriptPanel);
        assetContainer.add(graphicsPanel);
        
        setLocationRelativeTo(null);
        layoutDialog(-1);
        
        folderList.setAssetTree(assetTree);
        assetTree.setFolderList(folderList);
        
        assetFilterTextField.getDocument().addDocumentListener(new DocumentListener(){  
            public void insertUpdate(DocumentEvent e) {
                filterTextChanged();
            }

            public void removeUpdate(DocumentEvent e) {
                filterTextChanged();
            }

            public void changedUpdate(DocumentEvent e) {}
        });
    }
    
    public void setup(boolean readOnly, String defaultFilename, List<String> formatFilter){
        this.readOnly = readOnly;
        if(readOnly){
            setDialogButton(new String[]{"close"});
        }
        
        this.defaultFilename = defaultFilename;
        this.formatFilter = formatFilter;
        
        assetTree.setFormatFilter(formatFilter);
        setAsset(null);
    }
    
    public static String getAssetFilename(Frame parent, String defaultFilename, List<String> formatFilter){
        AssetManagerWindow window = AssetManagerWindow.getInstance();
        window.setup(false, defaultFilename, formatFilter);
        window.setVisible(true);
        return window.getCurrentAssetRelativeFilename();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        leftSplitPane = new javax.swing.JSplitPane();
        middleSplitPane = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        assetFilterTextField = new lib.editor.widget.textfield.IconTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        assetTree = new lib.editor.ui.assetmanager.AssetManagerAssetsTree();
        assetContainer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        folderList = new lib.editor.ui.assetmanager.AssetManagerAssetFolderList();
        buttonPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assets Manager");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setMinimumSize(new java.awt.Dimension(515, 360));
        mainPanel.setPreferredSize(new java.awt.Dimension(515, 360));
        mainPanel.setLayout(new java.awt.BorderLayout(8, 0));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        leftSplitPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        middleSplitPane.setResizeWeight(1.0);

        jPanel6.setMinimumSize(new java.awt.Dimension(160, 226));
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 226));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        assetFilterTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/find.png"))); // NOI18N
        assetFilterTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        assetFilterTextField.setMinimumSize(new java.awt.Dimension(20, 28));
        assetFilterTextField.setPreferredSize(new java.awt.Dimension(24, 28));
        jPanel5.add(assetFilterTextField);

        jPanel6.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(assetTree);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        middleSplitPane.setLeftComponent(jPanel6);

        assetContainer.setMinimumSize(new java.awt.Dimension(80, 0));
        assetContainer.setPreferredSize(new java.awt.Dimension(80, 0));
        assetContainer.setLayout(new javax.swing.BoxLayout(assetContainer, javax.swing.BoxLayout.LINE_AXIS));
        middleSplitPane.setRightComponent(assetContainer);

        leftSplitPane.setRightComponent(middleSplitPane);

        jPanel4.setMinimumSize(new java.awt.Dimension(160, 226));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 226));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        folderList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(folderList);

        jPanel4.add(jScrollPane4);

        leftSplitPane.setLeftComponent(jPanel4);

        jPanel2.add(leftSplitPane);

        mainPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        buttonPanel.setAutoscrolls(true);
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.PAGE_AXIS));

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setAlignmentX(0.5F);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(refreshButton);
        buttonPanel.add(filler1);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        String folderSelectedText = null;
        if(folderList.getCurrentItem() != null){
            folderSelectedText = folderList.getCurrentItem().getText();
        }
        
        String assetSelectedPath = null;
        if(assetTree.getCurrentItem() != null){
            assetSelectedPath = ((FilePathTreeItem) assetTree.getCurrentItem()).getFilePath();
        }
        
        folderList.refresh();
        if(folderSelectedText != null){
            folderList.setCurrentItem(folderSelectedText);
        }
        
        if(assetSelectedPath != null){
            assetTree.setCurrentItemByPath(assetSelectedPath);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assetContainer;
    private lib.editor.widget.textfield.IconTextField assetFilterTextField;
    private lib.editor.ui.assetmanager.AssetManagerAssetsTree assetTree;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.Box.Filler filler1;
    private lib.editor.ui.assetmanager.AssetManagerAssetFolderList folderList;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane leftSplitPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane middleSplitPane;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables

    public void ok() {
        if(!isCurrentAssetValid()){
            return;
        }
        super.ok();
    }

    /*
    public void cancel() {
        super.
    }*/

    @Override
    public void refresh() {
        folderList.refresh();
        assetTree.refresh();
        
        if(defaultFilename != null){
            setCurrentPath(defaultFilename);
            defaultFilename = null;
        }
    }

    @Override
    public JPanel getMainPanel() {
        return mainPanel;
    }
    
    public void saveSettings(){
        if(ProjectMgr.isProjectOpen()){
            Properties prop = ProjectMgr.getProperties();
            String prefix = "AssetManagerWindow_";
            SwingUtil.saveWindowBasics(prop, prefix, this);
            prop.setProperty(prefix + "LeftSplitPane", String.valueOf(leftSplitPane.getDividerLocation()));
            prop.setProperty(prefix + "MiddleSplitPane", String.valueOf(middleSplitPane.getDividerLocation()));
            assetTree.expandMemorizer.save("AssetManagerWindow_AssetTree." + AppMgr.getExtension("settings file"));
        }
    }
    
    public void loadSettings(){
        Properties prop = ProjectMgr.getProperties();
        String prefix = "AssetManagerWindow_";
        SwingUtil.loadWindowBasics(prop, prefix, this);
        try{
            leftSplitPane.setDividerLocation( Integer.parseInt(prop.getProperty(prefix + "LeftSplitPane")));
            middleSplitPane.setDividerLocation( Integer.parseInt(prop.getProperty(prefix + "MiddleSplitPane")));
        }catch(NumberFormatException e){}
        assetTree.expandMemorizer.load("AssetManagerWindow_AssetTree." + AppMgr.getExtension("settings file"));
    }
    
    public void dispose(){
        audioPanel.clearAudio();
        saveSettings();
        super.dispose();
    }
    
    public void setVisible(boolean visible){
        if(visible){
            //WidgetMgr.ASSET_MANAGER_WINDOW = this;
            loadSettings();
        }
        else{
            instance = null;
        }
        super.setVisible(visible);
    }
    
    public void setCurrentPath(String relativePath){
        File file = new File(ProjectMgr.getAssetsPath() ,relativePath);
        
        if(!file.exists()){return;}
        
        while(file.getParent() != null && !file.getParent().equals(ProjectMgr.getAssetsPath())){
            file = file.getParentFile();
        }
        String folder = file.getName();
        folderList.setCurrentItem(folder);
        
        assetTree.setCurrentItemByPath(relativePath);
    }
    

    
    public void clearFilter(){
        assetFilterTextField.setText("");
    }
    
    public void filterTextChanged(){
        String filterText = assetFilterTextField.getText();
        assetTree.setFilterText(assetFilterTextField.getText());
        assetTree.refresh();
    }
    
    public boolean isCurrentAssetValid(){
        if(readOnly){
            return false;
        }
        
        String relativePath = getCurrentAssetRelativeFilename();
        if(relativePath == null){
            return false;
        }
        
        File file = new File(ProjectMgr.getAssetsPath(), relativePath);
        
        if(file.isDirectory()){
            return false;
        }
        
        return true;
    }
    
    public String getCurrentAssetRelativeFilename(){
        if((FilePathTreeItem)assetTree.getCurrentItem() == null){
            return null;
        }
        return ((FilePathTreeItem)assetTree.getCurrentItem()).getFilePath();
    }


    public void setAsset(String relativePath) {
        audioPanel.clearAudio();
        audioPanel.setVisible(false);
        scriptPanel.setVisible(false);
        graphicsPanel.setVisible(false);
        //assetContainer.removeAll();
        if(relativePath == null){
            return;
        }
        //textAreaScrollPane.setVisible(false);
        //audioContainer.setVisible(false);
        //String relativePath = ((FilePathTreeItem)assetTree.getCurrentItem()).getFilePath();
        //String assetPath = new File(ProjectMgr.getAssetsPath(), relativePath).getAbsolutePath();

        //boolean isSound = folderList.getCurrentItem().getText().equals("Sounds");
        
        File file = new File(ProjectMgr.getAssetsPath(), relativePath);
        
        String ext = FilenameUtils.getExtension(file.getName());
        
        if(Cst.VALID_IMAGE_FORMAT.contains(ext)){
            graphicsPanel.setAsset(file);
        }
        else if(Cst.VALID_SOUND_FORMAT.contains(ext)){
            boolean isSound = folderList.getCurrentItem().getText().equals("Sounds");
            audioPanel.setAsset(file, isSound);
        }
        else if(Cst.VALID_SCRIPT_FORMAT.contains(ext)){
            scriptPanel.setAsset(file);
        }
        
    }
    
    /*
    public void setImageAsset(File file){
        //assetFiller.setVisible(false);
    }
    
    public void setAudioAsset(File file){
        //assetContainer.add(audioPanel);
        //audioPanel.setVisible(true);
        
        boolean isSound = folderList.getCurrentItem().getText().equals("Sounds");
        audioPanel.setAsset(file, isSound);
        //assetFiller.setVisible(true);
        //audioContainer.setVisible(true);
    }
    
    public void setTextAsset(File file){
        //assetContainer.add(textAreaScrollPane);
        //assetFiller.setVisible(false);
        //scriptPanel.setVisible(true);
        

    }*/
    
}
