/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui.assetmanager;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.files.FileHandle;
import java.io.File;
import lib.editor.mgr.ProjectManager;
import lib.editor.widget.tree.item.FilePathTreeItem;

/**
 *
 * @author gaetan
 */
public class AssetManagerAudioPanel extends javax.swing.JPanel {

    File assetFile;
    boolean isAssetSound;
            
    Sound sound;
    long lastSoundId;
    Music music;
    
    public AssetManagerAudioPanel() {
        initComponents();
    }
    
    public void clearAudio(){
        if(sound != null){
            sound.dispose();
            sound = null;
        }
        if(music != null){
            music.dispose();
            music = null;
        }
    }

    public void setAsset(File assetFile, boolean isSound){
        setVisible(true);
        this.assetFile = assetFile;
        isAssetSound = isSound;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        stopButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        volumeSlider = new javax.swing.JSlider();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel2 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        pitchSlider = new javax.swing.JSlider();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel5 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel6 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        audioPanel.setMaximumSize(new java.awt.Dimension(120, 32881));
        audioPanel.setMinimumSize(new java.awt.Dimension(120, 109));
        audioPanel.setPreferredSize(new java.awt.Dimension(120, 146));
        audioPanel.setLayout(new javax.swing.BoxLayout(audioPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 46));

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/stop.png"))); // NOI18N
        stopButton.setMargin(null);
        stopButton.setMaximumSize(new java.awt.Dimension(36, 36));
        stopButton.setMinimumSize(new java.awt.Dimension(36, 36));
        stopButton.setPreferredSize(new java.awt.Dimension(36, 36));
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/play_pause.png"))); // NOI18N
        playButton.setMargin(null);
        playButton.setMaximumSize(new java.awt.Dimension(36, 36));
        playButton.setMinimumSize(new java.awt.Dimension(36, 36));
        playButton.setPreferredSize(new java.awt.Dimension(36, 36));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton);

        audioPanel.add(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volume", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel9.add(filler2);

        volumeSlider.setMajorTickSpacing(10);
        volumeSlider.setMinorTickSpacing(5);
        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.setPaintTicks(true);
        volumeSlider.setValue(100);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        jPanel9.add(volumeSlider);
        jPanel9.add(filler3);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("100%");
        jPanel10.add(jLabel1);
        jPanel10.add(filler4);

        jLabel2.setText("50%");
        jPanel10.add(jLabel2);
        jPanel10.add(filler5);

        jLabel3.setText("0%");
        jPanel10.add(jLabel3);

        jPanel3.add(jPanel10);

        audioPanel.add(jPanel3);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pitch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel12.add(filler6);

        pitchSlider.setMajorTickSpacing(10);
        pitchSlider.setMaximum(150);
        pitchSlider.setMinimum(50);
        pitchSlider.setMinorTickSpacing(5);
        pitchSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        pitchSlider.setPaintTicks(true);
        pitchSlider.setValue(100);
        jPanel12.add(pitchSlider);
        jPanel12.add(filler7);

        jPanel11.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setText("150%");
        jPanel13.add(jLabel4);
        jPanel13.add(filler8);

        jLabel5.setText("100%");
        jPanel13.add(jLabel5);
        jPanel13.add(filler9);

        jLabel6.setText("50%");
        jPanel13.add(jLabel6);

        jPanel11.add(jPanel13);

        audioPanel.add(jPanel11);

        add(audioPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        clearAudio();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed

        if(!assetFile.exists()){
            return;
        }
        
        String assetPath = assetFile.getAbsolutePath();
        
        System.out.println(isAssetSound);

        clearAudio();

        if(isAssetSound){
            sound = Gdx.audio.newSound(new FileHandle(assetPath));
            lastSoundId = sound.play();
            sound.setVolume(lastSoundId, volumeSlider.getValue()/100f);
            sound.setPitch(lastSoundId, pitchSlider.getValue()/100f);
        }
        else{
            music = Gdx.audio.newMusic(new FileHandle(assetPath));
            music.setLooping(true);
            music.setVolume(volumeSlider.getValue()/100f);
            music.play();
        }

    }//GEN-LAST:event_playButtonActionPerformed

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        if(music != null){
            music.setVolume(volumeSlider.getValue()/100f);
        }
        if(sound != null){
            sound.setVolume(lastSoundId, volumeSlider.getValue()/100f);
        }
    }//GEN-LAST:event_volumeSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel audioPanel;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider pitchSlider;
    private javax.swing.JButton playButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
